CREATE TABLE IF NOT EXISTS visits (
 id TEXT PRIMARY KEY, started INTEGER NOT NULL, updated INTEGER NOT NULL,
 active_ms INTEGER NOT NULL DEFAULT 0, seq INTEGER NOT NULL DEFAULT 0,
 consent_version TEXT NOT NULL DEFAULT 'v1'
);
CREATE TABLE IF NOT EXISTS events (
 id INTEGER PRIMARY KEY AUTOINCREMENT, visit TEXT NOT NULL, at INTEGER NOT NULL, action TEXT NOT NULL,
 seq INTEGER NOT NULL, position INTEGER NOT NULL, UNIQUE(visit,seq,position)
);
CREATE INDEX IF NOT EXISTS visits_updated ON visits(updated);
CREATE INDEX IF NOT EXISTS events_visit ON events(visit);
CREATE INDEX IF NOT EXISTS events_at ON events(at);
CREATE TABLE IF NOT EXISTS erased (id TEXT PRIMARY KEY, until INTEGER NOT NULL);
